# Generated by Django 2.1.7 on 2019-07-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted_event',
            name='accepter_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='created_event',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
