# Generated by Django 2.1.7 on 2019-07-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0002_auto_20190724_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='created_event',
            name='description',
            field=models.TextField(default=None, max_length=5000, null=True),
        ),
    ]
